### PR TITLE
Add Nix and Flakes support

### PR DESCRIPTION
**Pull request by shymega**
This commit adds support for Nix Flakes.

Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

### CODE REVIEW

**Comment by Ralim** [comment]
Can we add a CI action to ensure these work somehow?

**Comment by shymega** [comment]
Yeah, for sure. I can add that.

**Comment by shymega** [comment]
In my latest CI revamp branch, this is implemented.

**Comment by shymega** [comment]
Closing, the branch got messed up. And too messy.

**Pull request closed without merging**
